/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Cased25519KeyPairResult {
  privateKey: Array<number>
  publicKey: Array<number>
  constructor(privateKey: Array<number>, publicKey: Array<number>)
}
export type CASED25519KeyPairResult = Cased25519KeyPairResult

export declare class CasrsaDigitalSignatureResult {
  publicKey: string
  privateKey: string
  signature: Array<number>
  constructor(publicKey: string, privateKey: string, signature: Array<number>)
}
export type CASRSADigitalSignatureResult = CasrsaDigitalSignatureResult

export declare class CasrsaKeyPairResult {
  privateKey: string
  publicKey: string
  constructor(privateKey: string, publicKey: string)
}
export type CASRSAKeyPairResult = CasrsaKeyPairResult

export declare class Casshaed25519DalekDigitalSignatureResult {
  publicKey: Array<number>
  signature: Array<number>
  constructor(publicKey: Array<number>, signature: Array<number>)
}
export type CASSHAED25519DalekDigitalSignatureResult = Casshaed25519DalekDigitalSignatureResult

export declare class CaSx25519SecretPublicKeyResult {
  publicKey: Array<number>
  secretKey: Array<number>
  constructor(publicKey: Array<number>, secretKey: Array<number>)
}
export type CASx25519SecretPublicKeyResult = CaSx25519SecretPublicKeyResult

export declare class HpkeEncryptResult {
  tag: Array<number>
  ciphertext: Array<number>
  encapsulatedKey: Array<number>
  constructor(tag: Array<number>, ciphertext: Array<number>, encapsulatedKey: Array<number>)
}

export declare class HpkeKeyResult {
  publicKey: Array<number>
  secretKey: Array<number>
  infoStr: Array<number>
  constructor(publicKey: Array<number>, secretKey: Array<number>, infoStr: Array<number>)
}

export declare function aes128Decrypt(aesKey: Array<number>, nonce: Array<number>, ciphertext: Array<number>): Array<number>

export declare function aes128Encrypt(aesKey: Array<number>, nonce: Array<number>, plaintext: Array<number>): Array<number>

export declare function aes128Key(): Array<number>

export declare function aes128KeyFromX25519SharedSecret(sharedSecret: Array<number>): Array<number>

export declare function aes256Decrypt(aesKey: Array<number>, nonce: Array<number>, ciphertext: Array<number>): Array<number>

export declare function aes256Encrypt(aesKey: Array<number>, nonce: Array<number>, plaintext: Array<number>): Array<number>

export declare function aes256Key(): Array<number>

export declare function aes256KeyFromX25519SharedSecret(sharedSecret: Array<number>): Array<number>

export declare function aesNonce(): Array<number>

export declare function argon2Hash(password: string): string

export declare function argon2Verify(hashedPassword: string, passwordToVerify: string): boolean

export declare function ascon128Decrypt(key: Array<number>, nonce: Array<number>, ciphertext: Array<number>): Array<number>

export declare function ascon128Encrypt(key: Array<number>, nonce: Array<number>, plaintext: Array<number>): Array<number>

export declare function ascon128KeyGenerate(): Array<number>

export declare function ascon128NonceGenerate(): Array<number>

export declare function bcryptHash(passwordToHash: string): string

export declare function bcryptVerify(hashedPassword: string, passwordToVerify: string): boolean

export declare function blake2Sha256(dataToHash: Array<number>): Array<number>

export declare function blake2Sha256Verify(dataToHash: Array<number>, dataToVerify: Array<number>): boolean

export declare function blake2Sha512(dataToHash: Array<number>): Array<number>

export declare function blake2Sha512Verify(dataToHash: Array<number>, dataToVerify: Array<number>): boolean

export declare function generateEd25519Keys(): Cased25519KeyPairResult

export declare function generateInfoStr(): Array<number>

export declare function generateRsaKeys(keySize: number): CasrsaKeyPairResult

export declare function hmacSign(key: Array<number>, message: Array<number>): Array<number>

export declare function hmacVerify(key: Array<number>, message: Array<number>, signature: Array<number>): boolean

export declare function hpkeDecrypt(ciphertext: Array<number>, privateKey: Array<number>, encappedKey: Array<number>, tag: Array<number>, infoStr: Array<number>): Array<number>

export declare function hpkeEncrypt(plaintext: Array<number>, publicKey: Array<number>, infoStr: Array<number>): HpkeEncryptResult

export declare function hpkeGenerateKeypair(): HpkeKeyResult

export declare function scryptHash(passwordToHash: string): string

export declare function scryptVerify(hashedPassword: string, passwordToVerify: string): boolean

export declare function sha256(dataToHash: Array<number>): Array<number>

export declare function sha256RsaDigitalSignature(rsaKeySize: number, dataToSign: Array<number>): CASRSADigitalSignatureResult

export declare function sha256RsaVerifyDigitalSignature(publicKey: string, dataToVerify: Array<number>, signature: Array<number>): boolean

export declare function sha256Verify(dataToHash: Array<number>, dataToVerify: Array<number>): boolean

export declare function sha512(dataToHash: Array<number>): Array<number>

export declare function sha512RsaDigitalSignature(rsaKeySize: number, dataToSign: Array<number>): CASRSADigitalSignatureResult

export declare function sha512RsaVerifyDigitalSignature(publicKey: string, dataToVerify: Array<number>, signature: Array<number>): boolean

export declare function sha512Verify(dataToHash: Array<number>, dataToVerify: Array<number>): boolean

export declare function signEd25519(privateKey: Array<number>, message: Array<number>): Array<number>

export declare function signRsa(privateKey: string, hash: Array<number>): Array<number>

export declare function verifyEd25519(publicKey: Array<number>, message: Array<number>, signature: Array<number>): boolean

export declare function verifyRsa(publicKey: string, hash: Array<number>, signature: Array<number>): boolean

export declare function x25519DiffieHellman(mySecretKey: Array<number>, usersPublicKey: Array<number>): Array<number>

export declare function x25519GenerateSecretAndPublicKey(): CASx25519SecretPublicKeyResult
