// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./index.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-android-arm64')
        const bindingPackageVersion = require('cas-typescript-sdk-android-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./index.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-android-arm-eabi')
        const bindingPackageVersion = require('cas-typescript-sdk-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./index.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-win32-x64-gnu')
        const bindingPackageVersion = require('cas-typescript-sdk-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./index.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-win32-x64-msvc')
        const bindingPackageVersion = require('cas-typescript-sdk-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./index.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-win32-ia32-msvc')
        const bindingPackageVersion = require('cas-typescript-sdk-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-win32-arm64-msvc')
        const bindingPackageVersion = require('cas-typescript-sdk-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./index.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('cas-typescript-sdk-darwin-universal')
      const bindingPackageVersion = require('cas-typescript-sdk-darwin-universal/package.json').version
      if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./index.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-darwin-x64')
        const bindingPackageVersion = require('cas-typescript-sdk-darwin-x64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-darwin-arm64')
        const bindingPackageVersion = require('cas-typescript-sdk-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./index.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-freebsd-x64')
        const bindingPackageVersion = require('cas-typescript-sdk-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-freebsd-arm64')
        const bindingPackageVersion = require('cas-typescript-sdk-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./index.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-x64-musl')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-x64-gnu')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./index.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-arm64-musl')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-arm64-gnu')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./index.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-arm-musleabihf')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-arm-gnueabihf')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./index.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-loong64-musl')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-loong64-gnu')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./index.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-riscv64-musl')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('cas-typescript-sdk-linux-riscv64-gnu')
          const bindingPackageVersion = require('cas-typescript-sdk-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./index.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-linux-ppc64-gnu')
        const bindingPackageVersion = require('cas-typescript-sdk-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./index.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-linux-s390x-gnu')
        const bindingPackageVersion = require('cas-typescript-sdk-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./index.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-openharmony-arm64')
        const bindingPackageVersion = require('cas-typescript-sdk-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./index.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-openharmony-x64')
        const bindingPackageVersion = require('cas-typescript-sdk-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./index.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('cas-typescript-sdk-openharmony-arm')
        const bindingPackageVersion = require('cas-typescript-sdk-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '1.0.53' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.53 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./index.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('cas-typescript-sdk-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.Cased25519KeyPairResult = nativeBinding.Cased25519KeyPairResult
module.exports.CASED25519KeyPairResult = nativeBinding.CASED25519KeyPairResult
module.exports.CasrsaDigitalSignatureResult = nativeBinding.CasrsaDigitalSignatureResult
module.exports.CASRSADigitalSignatureResult = nativeBinding.CASRSADigitalSignatureResult
module.exports.CasrsaKeyPairResult = nativeBinding.CasrsaKeyPairResult
module.exports.CASRSAKeyPairResult = nativeBinding.CASRSAKeyPairResult
module.exports.Casshaed25519DalekDigitalSignatureResult = nativeBinding.Casshaed25519DalekDigitalSignatureResult
module.exports.CASSHAED25519DalekDigitalSignatureResult = nativeBinding.CASSHAED25519DalekDigitalSignatureResult
module.exports.CaSx25519SecretPublicKeyResult = nativeBinding.CaSx25519SecretPublicKeyResult
module.exports.CASx25519SecretPublicKeyResult = nativeBinding.CASx25519SecretPublicKeyResult
module.exports.HpkeEncryptResult = nativeBinding.HpkeEncryptResult
module.exports.HpkeKeyResult = nativeBinding.HpkeKeyResult
module.exports.aes128Decrypt = nativeBinding.aes128Decrypt
module.exports.aes128Encrypt = nativeBinding.aes128Encrypt
module.exports.aes128Key = nativeBinding.aes128Key
module.exports.aes128KeyFromX25519SharedSecret = nativeBinding.aes128KeyFromX25519SharedSecret
module.exports.aes256Decrypt = nativeBinding.aes256Decrypt
module.exports.aes256Encrypt = nativeBinding.aes256Encrypt
module.exports.aes256Key = nativeBinding.aes256Key
module.exports.aes256KeyFromX25519SharedSecret = nativeBinding.aes256KeyFromX25519SharedSecret
module.exports.aesNonce = nativeBinding.aesNonce
module.exports.argon2Hash = nativeBinding.argon2Hash
module.exports.argon2HashParams = nativeBinding.argon2HashParams
module.exports.argon2Verify = nativeBinding.argon2Verify
module.exports.ascon128Decrypt = nativeBinding.ascon128Decrypt
module.exports.ascon128Encrypt = nativeBinding.ascon128Encrypt
module.exports.ascon128KeyGenerate = nativeBinding.ascon128KeyGenerate
module.exports.ascon128NonceGenerate = nativeBinding.ascon128NonceGenerate
module.exports.bcryptHash = nativeBinding.bcryptHash
module.exports.bcryptHashParams = nativeBinding.bcryptHashParams
module.exports.bcryptVerify = nativeBinding.bcryptVerify
module.exports.blake2Sha256 = nativeBinding.blake2Sha256
module.exports.blake2Sha256Verify = nativeBinding.blake2Sha256Verify
module.exports.blake2Sha512 = nativeBinding.blake2Sha512
module.exports.blake2Sha512Verify = nativeBinding.blake2Sha512Verify
module.exports.generateEd25519Keys = nativeBinding.generateEd25519Keys
module.exports.generateInfoStr = nativeBinding.generateInfoStr
module.exports.generateRsaKeys = nativeBinding.generateRsaKeys
module.exports.hmacSign = nativeBinding.hmacSign
module.exports.hmacVerify = nativeBinding.hmacVerify
module.exports.hpkeDecrypt = nativeBinding.hpkeDecrypt
module.exports.hpkeEncrypt = nativeBinding.hpkeEncrypt
module.exports.hpkeGenerateKeypair = nativeBinding.hpkeGenerateKeypair
module.exports.scryptHash = nativeBinding.scryptHash
module.exports.scryptHashParams = nativeBinding.scryptHashParams
module.exports.scryptVerify = nativeBinding.scryptVerify
module.exports.sha256 = nativeBinding.sha256
module.exports.sha256RsaDigitalSignature = nativeBinding.sha256RsaDigitalSignature
module.exports.sha256RsaVerifyDigitalSignature = nativeBinding.sha256RsaVerifyDigitalSignature
module.exports.sha256Verify = nativeBinding.sha256Verify
module.exports.sha512 = nativeBinding.sha512
module.exports.sha512RsaDigitalSignature = nativeBinding.sha512RsaDigitalSignature
module.exports.sha512RsaVerifyDigitalSignature = nativeBinding.sha512RsaVerifyDigitalSignature
module.exports.sha512Verify = nativeBinding.sha512Verify
module.exports.signEd25519 = nativeBinding.signEd25519
module.exports.signRsa = nativeBinding.signRsa
module.exports.verifyEd25519 = nativeBinding.verifyEd25519
module.exports.verifyRsa = nativeBinding.verifyRsa
module.exports.x25519DiffieHellman = nativeBinding.x25519DiffieHellman
module.exports.x25519GenerateSecretAndPublicKey = nativeBinding.x25519GenerateSecretAndPublicKey
